# Generated by Django 3.1.2 on 2022-06-02 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startpage', '0019_muser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentVehichle',
            new_name='Shops',
        ),
    ]
