# Generated by Django 3.1.2 on 2022-06-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0020_auto_20220602_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raja',
        ),
    ]
