# Generated by Django 3.1.2 on 2022-11-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0022_auto_20220602_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='hdstatus',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='shop_photo',
        ),
    ]
