# Generated by Django 3.1.2 on 2022-11-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0023_auto_20221114_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='whatsapp_no',
            field=models.DateField(),
        ),
    ]
