# Generated by Django 3.1.2 on 2022-11-13 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0024_auto_20221114_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='whatsapp_no',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
