# Generated by Django 3.1.2 on 2022-11-20 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0026_remove_shops_whatsapp_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='Date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Proposal Date(mm/dd/yyyy'),
            preserve_default=False,
        ),
    ]
