# Generated by Django 4.0 on 2022-12-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('startpage', '0028_shops_status2_alter_shops_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shops',
            new_name='Proposals',
        ),
    ]
